### ISSUE TITLE
composer create-project namelesscoder/patternlab-fluid-edition thows InvalidArgumentException

### ISSUE THREAD

**Issue by jmverges** [NamelessCoder/patternlab-fluid-edition#2]
Hi there,

After composer create-project namelesscoder/patternlab-fluid-edition thows 

```
[InvalidArgumentException]                                                            
  Could not find package namelesscoder/patternlab-fluid-edition with stability stable. 
```

**Comment by NamelessCoder** [comment]
Until a true 1.0.0 version is released you will have add `-s dev` to the composer create-project command. This allows dev stability as base for the project. Won't be necessary when the final release is made!

**Comment by jmverges** [comment]
uhm, maybe could be good to have it in the readme until true 1.0.0 is released :D Thanks I will try it right away
