### ISSUE TITLE
Featureset

### ISSUE THREAD

**Issue by saneinsaner** [NamelessCoder/patternlab-fluid-edition#3]
When I use extended template names for hidden patterns (filename starts with underscore) or states (filename has @[state] appendix) the render viewhelper won’t include the pattern. Is there a way to achieve this behaviour?

**Comment by NamelessCoder** [comment]
This one is a problem from Fluid - it currently has a bug in which a method, which is public API but not used by Fluid itself, did not resolve partial template files recursively.

You can follow the status of that bug on https://github.com/TYPO3/Fluid/pull/348, or use the diff from there to apply the fix in your project until it gets included in a release.
