### ISSUE TITLE
Counting references

### ISSUE THREAD

**Issue by saneinsaner** [NamelessCoder/patternlab-fluid-edition#4]
I included a pattern with
`<f:render partial="00-atoms/02-text/01-text.fluid" arguments="{text: 'Foobar baz'}" />`
In the generated styleguide I don’t find this reference (the ... pattern contains the following patterns: ... The ... pattern is included in the following patterns). Is this feature not implemented yet or did I miss something?

**Comment by NamelessCoder** [comment]
Solution coming right up :)

**Comment by NamelessCoder** [comment]
Solved by release 1.0.0 of https://github.com/NamelessCoder/patternlab-fluid-patternengine, but note that actually rendering the atoms will require patch https://github.com/TYPO3/Fluid/pull/348.
