### ISSUE TITLE
Uncaught SyntaxError: Unexpected token p in patternlab-pattern.min.js

### ISSUE THREAD

**Issue by gkaplick** [NamelessCoder/patternlab-fluid-edition#6]
Currently im testing the fluid-edition and recieved following error in basic configuration:

```
Uncaught SyntaxError: Unexpected token p in JSON at position 1
    at JSON.parse (<anonymous>)
    at patternlab-pattern.min.js?1571403609:formatted:9
```
the error-break is at line 23 of patternlab-pattern.js:
patternData = document.getElementById('sg-pattern-data-footer').innerHTML;
  patternData = JSON.parse(patternData);

if i console.log the content of patternData, i get:
"{patternData -> f:format.raw()}"

i didnt figured out the mistake, but i hope it helps for evaluating the problem

kind regards

**Comment by NamelessCoder** [comment]
Hi @gkaplick,

It almost sounds like the JS is reading a template file that was not rendered by Fluid and therefore contains the Fluid source instead of the rendered `{patternData}` variable. Can you tell me a bit about how you use the PL edition - how you edit, generate and view the files?

**Comment by NamelessCoder** [comment]
Fixed by https://github.com/NamelessCoder/patternlab-fluid-styleguidekit/commit/b6b12666037c762aedbd45cbe8653a202247d63c, new version 1.0.1 tagged for the styleguide kit. You should be able to `composer update` your project and replace the styleguide, then it should work.
